### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Application is crashing while changing profile picture.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#674]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on user icon to reveal profile view.
3: Tap on profile picture icon and change the profile picture.
4: Repeat step-3 more than 5 times.
5: Check if application is crashing.

Expected result: Application should not crash while changing profile picture.

Actual result: Application is crashing while changing profile picture.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iN01vaDRnajZoaGc

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

I have tried more than 15 times and everytimes profile picture change smoothly and successfully

**Comment by ayaadel87** [comment]
@xiuie : i couldnot change profile picture of user, it keeps loading and picture is not updated
 issue for build [1.6.0-r18 (78)] on sony z2(6.0.1)

**Comment by ayaadel87** [comment]
@xiuie : issue is fixed in v1.6.0-r22 (82)  on sony z2(6.0.1)

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r23 (83)] on Samsung Galaxy S4 / 5.0.1 and Samsung Galaxy Note 4 / 6.0.1.

**Comment by Aishwarya-Testershub** [comment]
@xiuie  I can still reproduce this issue for build [2.0.4(104)] on Samsung Galaxy S6 / 6.0.1
After crash relaunch the app. Continuous loading process display on "Profile Picture".
