### ISSUE TITLE
[2.0.3-r9 (100)] Asus Zenfone Go / Android 5.1 - Wrong message display - Sign out from lomotif -> search for user and follow and unfollow user

### ISSUE THREAD

**Issue by Priyanka-SoftwaresDoneRight** [Lomotif/lomotif-android-issues#829]
Frequency: Every time

Pre-requisite: User should be logged out from lomotif app account

Action:
1. Launch the app
2. Log out from Lomotif app account
3. Tap on User search icon
4. Search for any user (for example "pari")
5. Double tap on "Follow" button
6. Popup "You are not logged in" will display
7. Click on Cancel button in popup
8. Another popup including two options "Unfollow" and "Cancel" will display
9. Select "Unfollow" from popup
10. Check whether message "Failed unfollowing @pari. Try again in few moments." or not

Expected result: 
1. Even if user double clicks on "follow" button, button should be disabed or not allowed user to double click on it
2. No error message should be displayed

Actual result:
1. User can tap and double click on follow button
2. Error message "Failed unfollowing @pari. Try again in few moments." displays

![screenshot_2017-01-07-21-25-41](https://cloud.githubusercontent.com/assets/24950381/21743194/554d9e56-d523-11e6-85a0-2bbb792a435a.png)

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build[2.0.3-r9(100)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.3-r9 (100)] on Samsung Galaxy S6 / 6.0.1

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue every time for build [2.0.3-r9 (100)] on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.0.3-r10 (101)] on Asus Zenfone Go / Android 5.1 and on Sony xperia Z / Android 5.1.1

This issue has been resolved for build [2.0.3-r10 (101)].

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.3-r10 (101)] on Google Pixel / 7.1.1.

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [2.0.5-r5 (115)] on Samsung Galaxy Note 4 / 6.0.1.
