### ISSUE TITLE
[1.0.15] Samsung galaxy S4 / Android 4.4.2: My Video & Find Music screens - "An error has occured" message displayed if user try to make a search w/o internet connection

### ISSUE THREAD

**Issue by kcherkas** [Lomotif/lomotif-android-issues#86]
[1.0.15] Samsung galaxy S4 / Android 4.4.2: My Video & Find Music screens - "An error has occured" message displayed if user try to make a search w/o internet connection

Preconditions: disabled internet connection
Frequency: Every Time
1. make sure what internet connection is disabled
2. run application
3. make search at My Video & Find Music screens

Expected results: no error or at least correct message displayed like "No internet connection"
Actual results: "An error has occured" message displayed

[search_error.txt](https://github.com/Lomotif/lomotif-android-issues/files/205942/search_error.txt)

P.S. misspelling in error text
Now text is "An error has occured" 
Should be "An error has occurred"

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 Similar issue as #48

**Comment by jpaulo1205** [comment]
Note: Fixed in 1.0.16

**Comment by kcherkas** [comment]
Checked in v1.0.16 at Samsung galaxy S4, android 4.4.2.
Only typo in "An error has occurred"  was corrected. User still see "An error has occurred" text if he make search w/o internet connection. "No internet connection" message still not implemented

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.0.18 on Asus Nexus 7 Android 5.1.1.
